name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Connect & Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Ð£ÐºÐ°Ð·Ñ‹Ð²Ð°ÐµÐ¼ Ð¿ÑƒÑ‚ÑŒ Ð´Ð¾ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð°
            DEPLOY_DIR="/opt/probhub/microserv"

            # Ð•ÑÐ»Ð¸ Ð¿Ð°Ð¿ÐºÐ° Ð½Ðµ ÑÑƒÑ‰ÐµÑÑ‚Ð²ÑƒÐµÑ‚ Ð¸Ð»Ð¸ Ð½Ðµ ÑÐ²Ð»ÑÐµÑ‚ÑÑ git-Ñ€ÐµÐ¿Ð¾Ð·Ð¸Ñ‚Ð¾Ñ€Ð¸ÐµÐ¼ â€” ÑÐ¾Ð·Ð´Ð°Ñ‘Ð¼ Ð¸ ÐºÐ»Ð¾Ð½Ð¸Ñ€ÑƒÐµÐ¼
            if [ ! -d "$DEPLOY_DIR/.git" ]; then
            echo "ðŸ“ ÐŸÐ°Ð¿ÐºÐ° Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð° Ð¸Ð»Ð¸ Ð½Ðµ Ð¸Ð½Ð¸Ñ†Ð¸Ð°Ð»Ð¸Ð·Ð¸Ñ€Ð¾Ð²Ð°Ð½ git. Ð¡Ð¾Ð·Ð´Ð°Ñ‘Ð¼..."
            sudo mkdir -p "$DEPLOY_DIR"
            sudo chown -R \$USER:\$USER "$DEPLOY_DIR"
            git clone https://github.com/${{ github.repository }} "$DEPLOY_DIR"
            else
            echo "âœ… ÐŸÐ°Ð¿ÐºÐ° Ð½Ð°Ð¹Ð´ÐµÐ½Ð°. ÐžÐ±Ð½Ð¾Ð²Ð»ÑÐµÐ¼ Ð¿Ñ€Ð¾ÐµÐºÑ‚..."
            cd "$DEPLOY_DIR"
            git pull
            fi

            cd "$DEPLOY_DIR"
            docker compose up --build -d
        EOF    

